---
title: "eeg_statistical_analysis_with_categorical_data"
---
```{r Initialization}

rm(list=ls())

library(yaml)
library(ggplot2)
library(feather)
library(lme4)
library(simr)
library(here)
library(sjPlot)
library(writexl)
library(ggpubr)
library(sjmisc)

# Read the configuration file
config <- yaml.load_file("../config.yml")

eeg_r_dataset_path <- here(config$engagement_index_force_dataset)
df <- read_feather(eeg_r_dataset_path)
df <- na.omit(df)
config$epoch_length

# Convert to factor
df$control_type <- as.factor(df$control_type)
df$hand_type <- as.factor(df$hand_type)
df$subject <- as.factor(df$subject)

response <- df$beta_alpha_theta
df['output'] <- response
```

```{r Analysis under non dominant hand with no force as reference}
# Here the random effect is only the intercept

# Leave the subject 8 from all the analysis
subject_to_leave <- config$subjects[8]
df_temp <- df[!(df$subject==subject_to_leave),]

# Select non-dominant hand
df_non_dominant <-  df_temp[df_temp[, 'hand_type'] == 'non_dominant',]
response <- df_non_dominant$output
df_non_dominant$control_type <- relevel(df_non_dominant$control_type, "error_reduction") # set the reference level

# Fit the mixed effect model
model <- glmer(response ~ control_type + (1 | subject),
              data = df_non_dominant, family = gaussian(link = log))
summary(model)
tab_model(model)

# Correlation analysis
resp <- log(response)
weighted_res <- model@resp$wtres
subjects <- unique(df_non_dominant$subject)

test <- c()
for (subject in subjects){
  id <- df_non_dominant$subject == subject
  test[subject] <- cor(resp[id], weighted_res[id], method = c("pearson"))
}
test
mean(test)
```



```{r Analysis under dominant hand using control type}
# Leave the subject 8 from all the analysis
subject_to_leave <- config$subjects[8]
df_temp <- df[!(df$subject==subject_to_leave),]

# Select the dominant hand
df_dominant <-  df_temp[df_temp[, 'hand_type'] == 'dominant',]
response <- df_dominant$output
df_dominant$control_type <- relevel(df_dominant$control_type, "no_force")

# Fit the mixed effect model
model <- glmer(response ~ control_type  + (1 | subject),
               data = df_dominant, family = gaussian(link = log))
summary(model)
tab_model(model)

# Correlation analysis
resp <- log(response)
weighted_res <- model@resp$wtres
subjects <- unique(df_dominant$subject)

test <- c()
for (subject in subjects){
  id <- df_dominant$subject == subject
  test[subject] <- cor(resp[id], weighted_res[id], method = c("pearson"))
}
test
mean(test)

```


```{r Analysis using both control type and hand type as factors}
# Leave the subject 8 from all the analysis
subject_to_leave <- config$subjects[8]
df_both_hands <- df[!(df$subject==subject_to_leave),]


# Set the reference levels
df_both_hands$control_type <- relevel(df_both_hands$control_type, "no_force")
df_both_hands$hand_type <- relevel(df_both_hands$hand_type, "dominant")
response <- df_both_hands$output

# Fit the mixed effect model
model <- glmer(response ~ control_type*hand_type + (1 | subject),
               data = df_both_hands, family = gaussian(link = log))
summary(model)
tab_model(model)

# Correlation analysis
resp <- log(response)
weighted_res <- model@resp$wtres
subjects <- unique(df_both_hands$subject)

test <- c()
for (subject in subjects){
  id <- df_both_hands$subject == subject
  test[subject] <- cor(resp[id], weighted_res[id], method = c("pearson"))
}
test
mean(test)
```



```{r Analysis under non dominant hand using control type but with slope as random effect}

# Leave subject 8 from all the analysis
subject_to_leave <- config$subjects[8]
df_temp <- df[!(df$subject==subject_to_leave),]

# Select the hand type and response
df_non_dominant <-  df_temp[df_temp[, 'hand_type'] == 'non_dominant',]
df_non_dominant$control_type <- relevel(df_non_dominant$control_type, "no_force")
response <- df_non_dominant$output

model <- glmer(response ~ control_type + (control_type | subject),
               data = df_non_dominant, family = gaussian(link = log))
summary(model)
tab_model(model)

# Correlation analysis
resp <- log(response)
weighted_res <- model@resp$wtres
subjects <- unique(df_non_dominant$subject)

test <- c()
for (subject in subjects){
  id <- df_non_dominant$subject == subject
  test[subject] <- cor(resp[id], weighted_res[id], method = c("pearson"))
}
test
mean(test)
```


```{r Analysis under dominant hand using control type but with slope as random effect}

# Leave subject 8 from all the analysis
subject_to_leave <- config$subjects[8]
df_temp <- df[!(df$subject==subject_to_leave),]

# Select the hand type and response
df_dominant <-  df_temp[df_temp[, 'hand_type'] == 'dominant',]
df_dominant$control_type <- relevel(df_dominant$control_type, "no_force")
response <- df_dominant$output

model <- glmer(response ~ control_type + (control_type | subject),
               data = df_dominant, family = gaussian(link = log))
summary(model)
tab_model(model)

# Correlation analysis
resp <- log(response)
weighted_res <- model@resp$wtres
subjects <- unique(df_dominant$subject)

test <- c()
for (subject in subjects){
  id <- df_dominant$subject == subject
  test[subject] <- cor(resp[id], weighted_res[id], method = c("pearson"))
}
test
mean(test)
```


```{r Analysis under both hand using control type but with slope as random effect}

# Leave subject 8 from all the analysis
subject_to_leave <- config$subjects[8]
df_both_hand <- df[!(df$subject==subject_to_leave),]

# Select the hand type and response
df_both_hand $control_type <- relevel(df_both_hand$control_type, "no_force")
response <- df_both_hand$output

model <- glmer(response ~ control_type*hand_type + (hand_type | subject),
               data = df_both_hand, family = gaussian(link = log))
summary(model)
tab_model(model)

# Correlation analysis
resp <- log(response)
weighted_res <- model@resp$wtres
subjects <- unique(df_both_hand$subject)

test <- c()
for (subject in subjects){
  id <- df_both_hand$subject == subject
  test[subject] <- cor(resp[id], weighted_res[id], method = c("pearson"))
}
test
mean(test)
```