---
title: "eeg_statistical_analysis_with_categorical_data"
---
```{r Initialization}

rm(list=ls())

library(yaml)
library(ggplot2)
library(feather)
library(lme4)
library(simr)
library(here)
library(sjPlot)
library(writexl)
library(ggpubr)

# Read the configuration file
config <- yaml.load_file("../config.yml")

eeg_r_dataset_path <- here(config$engagement_index_force_dataset)
df <- read_feather(eeg_r_dataset_path)
df <- na.omit(df)
config$epoch_length

# Convert to factor
df$control_type <- as.factor(df$control_type)
df$hand_type <- as.factor(df$hand_type)
df$subject <- as.factor(df$subject)

response <- df$beta_alpha_theta
df['output'] <- response

df$abs_force <- abs(df$total_force)

subject_to_leave <- config$subjects[8]
df <- df[!(df$subject==subject_to_leave),]

# Write to excel file
write_xlsx(df, 'engagement_index_with_abs_force.xlsx')
```

```{r Analysis using absoluate force, control type and hand type as the factors}
# Here the random effect is only the intercept

# Leave the subject 8 from all the analysis
subject_to_leave <- config$subjects[8]
df_temp <- df[!(df$subject==subject_to_leave),]
#df_temp <- df_temp[!(df_temp$control_type=='no_force'),]

# Add the absolute force as a factor
df_temp$abs_force <- abs(df_temp$total_force)

df_both_hand <- df_temp
response <- df_both_hand$output


df_both_hand$control_type <- relevel(df_both_hand$control_type, "no_force") # set the reference level
df_both_hand$hand_type <- relevel(df_both_hand$hand_type, "dominant") # set the

# Fit the mixed effect model
model <- glmer(response ~ control_type*abs_force*hand_type + (hand_type | subject),
              data = df_both_hand, family = gaussian(link = log))
summary(model)
tab_model(model)

# Correlation analysis
resp <- log(response)
weighted_res <- model@resp$wtres
subjects <- unique(df_both_hand$subject)

test <- c()
for (subject in subjects){
  id <- df_both_hand$subject == subject
  test[subject] <- cor(resp[id], weighted_res[id], method = c("pearson"))
}
test
mean(test)
```


```{r Analysis of baseline between dominant and non-dominant}
# Here the random effect is only the intercept

# Leave the subject 8 from all the analysis
subject_to_leave <- config$subjects[8]
df_temp <- df[!(df$subject==subject_to_leave),]

# Select only the no_force data
df_both_hands <- df_temp[(df_temp$control_type=="no_force"),]

# Set reference level and response
df_both_hand$control_type <- relevel(df_both_hand$control_type, "no_force")
response <- df_both_hand$output

# Fit the mixed effect model
model <- glmer(response ~ hand_type + (1 | subject),
              data = df_both_hand, family = gaussian(link = log))
summary(model)
tab_model(model)
```

```{r Analysis of baseline between dominant and non-dominant}
# Here the random effect is only the intercept

# Leave the subject 8 from all the analysis
subject_to_leave <- config$subjects[8]
df_temp <- df[!(df$subject==subject_to_leave),]

# Select only the no_force data
df_both_hands <- df_temp[(df_temp$control_type=="no_force"),]
df_hand <- aggregate(.~hand_type+subject, df_both_hands, mean)
response <- df_hand$output

# Anova test between dominant and non-dominant hand
aov.out = aov(response ~ hand_type, data=df_hand)
summary(aov.out)
```


```{r Analysis to identify the effect of hand type}
# Here the random effect is only the intercept

# Leave the subject 8 from all the analysis
subject_to_leave <- config$subjects[8]
df_temp <- df[!(df$subject==subject_to_leave),]
df_temp <- df_temp[!(df_temp$control_type=='no_force'),]

# Add the absolute force as a factor
df_temp$abs_force <- abs(df_temp$total_force)

df_both_hand <- df_temp
response <- df_both_hand$output
df_both_hand$hand_type <- relevel(df_both_hand$hand_type, "dominant") # set the

#--------------------------------------------------------#
# Fit the mixed effect model
model_with <- glmer(response ~ control_type*abs_force*hand_type + (1 | subject),
              data = df_both_hand, family = gaussian(link = log))
#--------------------------------------------------------#
# Fit the mixed effect model
model_without <- glmer(response ~ control_type*abs_force + (1 | subject),
              data = df_both_hand, family = gaussian(link = log))


# Form a new dataframe
df_both_hand$with <- model_with@resp$wtres
df_both_hand$without <- model_without@resp$wtres

mean(df_both_hand$with)
mean(df_both_hand$without)

#p1 <- density(df_both_hand$with)              
#p2 <- density(df_both_hand$without)
#plot(p1)
#lines(p2)

aov.out = aov(with ~ without, data=df_both_hand)
summary(aov.out)
```
