---
title: "R Notebook"
output: html_notebook
---

```{r}
library(yaml)
library(ggplot2)
library(feather)
library(lme4)
library(simr)
library(here)
library(sjPlot)
library(sjmisc)

# Read the configuration path
config <- yaml.load_file("../config.yml")

emg_r_dataset_path <- here(config$emg_r_dataset)
df <- read_feather(emg_r_dataset_path)
df <- na.omit(df)
config$epoch_length

# Convert to factor
df$control_type <- as.factor(df$control_type)
df$hand_type <- as.factor(df$hand_type)
df$subject <- as.factor(df$subject)
```

```{r Response}
response <- df$rms
df['output'] <- response
```


```{r Prior analysis}
df$hand_type <- relevel(df$hand_type, "dominant")
engagement.model <- glmer(response ~ 1 + (1 | df$hand_type), data = df, family = gaussian(link = log))
summary(engagement.model)
```


```{r Linear model 1 with both dominant and non_dominant hand type}
response <- df$output
df$control_type <- relevel(df$control_type, "no_force")
df$hand_type <- relevel(df$hand_type, "dominant")
model1 <- glmer(response ~ control_type + (1 | subject),
               data = df, family = gaussian(link = log))
summary(model1)
```

```{r Linear model 1 using only dominant hand}
df_dominant <- df[df[, 'hand_type'] == 'dominant',]
response <- df_dominant$output
model2 <- glmer(response ~ control_type + (1 | subject),
               data = df_dominant, family = gaussian(link = log))
summary(model2)
```


```{r Linear model 2 using only non dominant hand}
df_dominant <- df[df[, 'hand_type'] == 'non_dominant',]
response <- df_dominant$output
model3 <- glmer(response ~ control_type + (1 | subject),
               data = df_dominant, family = gaussian(link=log))
summary(model3)
```

